version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - install-purescript:
          name: Install purescript
          command: npm install -g purescript@0.13.3
      - install-spago:
          name: Install spago
          command: npm install -g spago
      - install-dependencies:
          name: Install dependencies
          command: make install-dev
      - run-unit-tests:
          name: Run unit tests
          command: make test-unit
