version: 2

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: mechpig/purescript:wip
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make install-dev
      - run:
          name: Run unit tests
          command: make test
